import Link from "next/link";

const policyContent: Record<string, { eyebrow: string; title: string; intro: string; sections: Array<[string, string]> }> = {
  terms: { eyebrow: "Trust / Terms", title: "Terms of service", intro: "These terms describe how Best in Daman provides fixed-price local digital advertising and sponsored visibility.", sections: [["The service", "Best in Daman provides time-bound promotional placements and listing visibility for businesses, creators, events, services, and community projects in Daman. Campaigns are not auctions, bids, contests, or guarantees of a particular ranking or outcome."], ["Submissions and review", "A campaign submission is pending until reviewed and approved. We may reject, edit for clarity, pause, or remove a campaign that does not meet our advertising guidelines or that points to an unsafe, misleading, unavailable, or unrelated destination."], ["Your responsibility", "You are responsible for the accuracy of the listing details, the rights to the submitted destination, and the goods or services promoted. Best in Daman does not become the seller of those goods or services."], ["Reporting", "We report measured impressions, listing views, unique viewers, and tracked actions as separate metrics. Reporting is informational and does not promise conversions, sales, or a minimum audience."]] },
  privacy: { eyebrow: "Trust / Privacy", title: "Privacy policy", intro: "We collect the information needed to review, schedule, support, and report on a local advertising campaign.", sections: [["Information you provide", "This may include a listing name, destination URL, category, description, owner name, email or phone, preferred call-to-action, campaign dates, and payment references."], ["How we use it", "We use submission details to review campaigns, communicate with owners, schedule placements, process support requests, and produce campaign reporting. We do not publish owner contact details unless they are part of the submitted public destination."], ["Analytics", "Public and owner reporting uses event counters such as homepage impressions, listing impressions, listing views, unique viewers, website taps, WhatsApp taps, call taps, directions taps, Instagram visits, saves, and shares. We do not describe an impression as a person reached."], ["Retention and requests", "We retain campaign and payment records for operational, legal, and accounting needs. To request access, correction, or deletion where applicable, contact the team through the contact page."]] },
  refunds: { eyebrow: "Trust / Refunds", title: "Refund & cancellation", intro: "Our campaign packages are fixed-price and scheduled only after review and payment confirmation.", sections: [["Before approval", "You can request cancellation while a submission is pending. If no payment has been confirmed, there is nothing to refund."], ["After payment", "If we reject a campaign after payment because it does not meet our guidelines, we will record the reason and review a refund or alternative campaign date. Approved campaigns may be rescheduled where practical."], ["Once live", "Because a live placement has begun consuming a scheduled advertising window, refunds are considered case-by-case for material service issues, duplicate charges, or a platform-side failure. Contact us promptly with the campaign reference."], ["Payment records", "Manual bank transfer or business UPI payments remain pending until an admin confirms the reference. Never send card or UPI credentials through the campaign description field."]] },
  guidelines: { eyebrow: "Trust / Advertising", title: "Advertising guidelines", intro: "Best in Daman is designed to make local discovery more useful. These guidelines keep the board clear, safe, and relevant.", sections: [["Good fits", "Local businesses, independent creators, events, services, community projects, openings, offers, classes, and things to do in or meaningfully serving Daman."], ["Not accepted", "We do not accept illegal goods or services, unsafe or deceptive claims, hate or harassment, adult sexual services, malicious links, impersonation, misleading health or financial claims, or content that infringes another person’s rights."], ["Destination quality", "The submitted link should work, match the listing, and make the next step clear. We may request a replacement link or a clearer description before approval."], ["Editorial control", "Approval is a condition of publishing, not an endorsement. We may pause or remove a campaign if the destination changes, the content becomes misleading, or the campaign no longer meets these guidelines."]] },
};

export function generateStaticParams() { return Object.keys(policyContent).map((slug) => ({ slug })); }

export default async function PolicyPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const policy = policyContent[slug] ?? policyContent.terms;
  return <main className="simple-page"><header className="site-header shell"><Link className="brand-link" href="/"><span className="brand-lockup"><span className="brand-mark">B</span><span className="brand-wordmark">Best in <em>Daman</em></span></span></Link><Link className="button button-small button-dark" href="/">Back to home <span className="ui-icon">↗</span></Link></header><article className="shell simple-article policy-article"><div className="eyebrow">{policy.eyebrow}</div><h1>{policy.title}</h1><p className="simple-lede">{policy.intro}</p><div className="policy-sections">{policy.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div><Link className="text-link" href="/contact">Questions about this policy? Contact us <span className="ui-icon">↗</span></Link></article></main>;
}
