create extension if not exists pgcrypto;

create table if not exists public.campaign_packages (
  id text primary key,
  name text not null,
  placement text not null,
  duration_days integer not null check (duration_days > 0),
  price_inr integer not null check (price_inr > 0),
  use_case text not null,
  reporting_metrics text[] not null default '{}',
  created_at timestamptz not null default now()
);

insert into public.campaign_packages (id, name, placement, duration_days, price_inr, use_case, reporting_metrics)
values
  ('homepage', '24-hour Homepage Spotlight', 'Top of the Daman board', 1, 29, 'A new offer, event, opening, or time-sensitive announcement.', array['homepage impressions', 'tracked actions']),
  ('category', '7-day Category Spotlight', 'Featured in one category', 7, 149, 'Stay visible while people compare local places and services.', array['listing impressions', 'listing views', 'tracked actions']),
  ('feature', '30-day Local Business Feature', 'Featured listing + category board', 30, 399, 'Build a stronger local presence with a richer business profile.', array['unique viewers', 'listing views', 'tracked actions'])
on conflict (id) do nothing;

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  listing_name text not null,
  category text not null check (category in ('Food & drink', 'Things to do', 'Services', 'Community', 'Wellness', 'Shopping & stays')),
  description text not null,
  destination_url text not null,
  preferred_cta text not null default 'Visit website' check (preferred_cta in ('Call', 'WhatsApp', 'Directions', 'Instagram', 'Visit website')),
  owner_name text not null,
  contact_value text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'paused', 'deleted')),
  moderation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  package_id text not null references public.campaign_packages(id),
  status text not null default 'pending' check (status in ('pending', 'approved', 'active', 'paused', 'rejected', 'completed', 'cancelled')),
  requested_start_at timestamptz not null,
  start_at timestamptz,
  end_at timestamptz,
  total_price_inr integer not null check (total_price_inr > 0),
  rejection_reason text,
  cancellation_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_events (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  event_type text not null check (event_type in ('homepage_impression', 'listing_impression', 'listing_view', 'unique_viewer', 'website_tap', 'whatsapp_tap', 'call_tap', 'directions_tap', 'instagram_visit', 'save', 'share')),
  viewer_hash text,
  occurred_at timestamptz not null default now()
);

create table if not exists public.analytics_counters (
  listing_id uuid not null references public.listings(id) on delete cascade,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  event_type text not null,
  event_count bigint not null default 0 check (event_count >= 0),
  unique_count bigint not null default 0 check (unique_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (campaign_id, event_type)
);

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'moderator' check (role in ('moderator', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.payment_records (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  provider text not null default 'manual',
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
  amount_inr integer not null check (amount_inr > 0),
  provider_reference text,
  admin_notes text,
  refund_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_listings_public_status on public.listings (status, category);
create index if not exists idx_campaigns_active_dates on public.campaigns (status, start_at, end_at);
create index if not exists idx_campaigns_listing_id on public.campaigns (listing_id);
create index if not exists idx_listing_events_campaign_type on public.listing_events (campaign_id, event_type, occurred_at);
create index if not exists idx_payment_records_campaign_id on public.payment_records (campaign_id);

alter table public.campaign_packages enable row level security;
alter table public.listings enable row level security;
alter table public.campaigns enable row level security;
alter table public.listing_events enable row level security;
alter table public.analytics_counters enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.payment_records enable row level security;

create policy "packages are public" on public.campaign_packages for select to anon, authenticated using (true);

create policy "public can read approved active listings" on public.listings for select to anon, authenticated using (
  status = 'approved' and exists (
    select 1 from public.campaigns c
    where c.listing_id = listings.id and c.status = 'active'
      and c.start_at <= now() and c.end_at > now()
  )
);
create policy "public can submit pending listings" on public.listings for insert to anon, authenticated with check (status = 'pending');
create policy "owners can read their listings" on public.listings for select to authenticated using (owner_id = auth.uid());
create policy "admins manage listings" on public.listings for all to authenticated using (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid())) with check (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid()));

create policy "public can read active campaigns" on public.campaigns for select to anon, authenticated using (
  status = 'active' and start_at <= now() and end_at > now()
);
create policy "public can submit pending campaigns" on public.campaigns for insert to anon, authenticated with check (status = 'pending');
create policy "owners can read their campaigns" on public.campaigns for select to authenticated using (exists (select 1 from public.listings l where l.id = listing_id and l.owner_id = auth.uid()));
create policy "admins manage campaigns" on public.campaigns for all to authenticated using (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid())) with check (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid()));

create policy "public may record approved campaign events" on public.listing_events for insert to anon, authenticated with check (
  exists (select 1 from public.campaigns c where c.id = campaign_id and c.listing_id = listing_events.listing_id and c.status = 'active' and c.start_at <= now() and c.end_at > now())
);
create policy "admins read listing events" on public.listing_events for select to authenticated using (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid()));

create policy "owners read their counters" on public.analytics_counters for select to authenticated using (exists (select 1 from public.listings l where l.id = listing_id and l.owner_id = auth.uid()));
create policy "admins manage counters" on public.analytics_counters for all to authenticated using (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid())) with check (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid()));

create policy "admins read own profile" on public.admin_profiles for select to authenticated using (user_id = auth.uid());
create policy "owners read their payment records" on public.payment_records for select to authenticated using (exists (select 1 from public.campaigns c join public.listings l on l.id = c.listing_id where c.id = campaign_id and l.owner_id = auth.uid()));
create policy "admins manage payment records" on public.payment_records for all to authenticated using (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid())) with check (exists (select 1 from public.admin_profiles a where a.user_id = auth.uid()));
